### ISSUE TITLE
Check respectRobots before rejecting links

### ISSUE THREAD

**Issue by Redominus** [spatie/crawler#193]
https://github.com/spatie/crawler/blob/b16d4b2ddfd59ec395c878212ab80e96d4ba8d38/src/LinkAdder.php#L65-L67
Link rejection should check respectRobots flag before rejecting a nofollow link. 
Adding this code should be enough
```php
return $this->crawler->mustRespectRobots() && $link->getNode()->getAttribute('rel') === 'nofollow';

**Comment by danhunsaker** [comment]
Pretty sure robots configs are distinct from `nofollow` attributes and similar. Robots rules are meant to prevent automated crawling, by anything. The main purpose of the above-mentioned attributes is to prevent search engines from saying a resource is endorsed or otherwise recommended by the site operators/content producers. The two can be used together, singly, or not at all, but neither is directly tied the functionality or purposes of the other.

I'd recommend adding a distinct setting for this, and doing it via pull request rather than comment.

**Comment by freekmurze** [comment]
@Redominus  Feel free to, like @danhunsaker suggested, to submit a fully tested PR for this.
