### ISSUE TITLE
How to use multiple observers.

### ISSUE THREAD

**Issue by ash-25** [spatie/crawler#238]
Hello,
can anyone tell me what is the purpose of multiple observers.
will it increase crawl speed.?
can i use crawllogger class in multiple observers?

**Comment by Redominus** [comment]
[Observer pattern](https://en.wikipedia.org/wiki/Observer_pattern).

**Comment by BenMorel** [comment]
Multiple observers will not increase crawl speed, this is not their purpose.

**The purpose of an observer is to get notified of events** that occur:

- a URL will be crawled
- a URL has been successfully crawled
- a URL could not be crawled because of a network or HTTP error
- the crawl has finished

**The observer is where you put your own logic**, such as:

- store crawled URLs in a database
- scrap HTML documents to gather information
- etc.

You can do whatever you want with an observer, this is your realm. Logging, parsing, you name it.
