### ISSUE TITLE
The "shouldCrawl" method of the "CrawlProfile" interface is executed more than one time.

### ISSUE THREAD

**Issue by design-principles** [spatie/crawler#283]
I've installed version 4.6 of the crawler and ran into one problem.
The `shouldCrawl` method is executed twice.
`shouldCrawl` is executed twice when I pass 1 to the `setMaximumCrawlCount` method. When I pass 2, `shouldCrawl` is executed 4 times and so on.
Why this is happening? Is that a bug or a feature?

**Comment by brendt** [comment]
@design-principles It's called two times indeed:

- In `Crawler` > `startCrawling`  (line 386) > `addToCrawlQueue` (line 481)
- In `Crawler` > `startCrawling` (line 391) > `startCrawlingQueue` (line 430) > `getCrawlRequests` (line 460)

I'm not sure why the second check is done. @freekmurze you wrote it in back in 2016, but the commit messages says `very wip` 😂

@design-principles can you elaborate why you opened this issue? Are you running into any problems because of this?

**Comment by freekmurze** [comment]
lol #wip

**Comment by design-principles** [comment]
@brendt I've got some complex logic that is executed inside `shouldCrawl`. And yes, my script loses performance because of it.

**Comment by brendt** [comment]
@freekmurze do you think it's worth the risk removing the second check? All tests seem to work, though I'm a little hesitant because this is a very old piece of the codebase. A more sage approach would be to incorporate this change in a new major version, but I don't think we had any concrete plans for a major release soon.

**Comment by freekmurze** [comment]
Can you send a PR with this change. I'll test it out in Oh Dear. If everything works there, I'll merge the change and tag a new release.

**Comment by brendt** [comment]
@freekmurze here it is: https://github.com/spatie/crawler/pull/289

**Comment by freekmurze** [comment]
I think we need the existing logic to cover some edge cases.

@design-principles if you're doing some expensive work inside that `shouldCrawl` method, I suggest you manually cache the results somewhere.

**Comment by brendt** [comment]
@design-principles please refer to https://github.com/spatie/crawler/pull/289, we're going to leave the check in. 

To solve your problem, I suggest to cache the expensive logic, could be as simple as a static array, with a mapping of all URLs and whether they should be crawled or not.
