### ISSUE TITLE
setParseableMimeTypes() not working

### ISSUE THREAD

**Issue by flmommens** [spatie/crawler#352]
Hi,
I'm using spatie/crawler 4.7.5 with php 7.2

I'm trying to exclude non-html documents from the crawl with

`Crawler::create()->setParseableMimeTypes(['text/html'])
`

The documentation says this method "will prevent downloading the body of pages that have different mime types".
However, the crawl method of my Observer gets called with URL of images, so I assume images are still being crawled.

Is there something I haven't understood?
Thanks

**Comment by freekmurze** [comment]
This test proves that the functionality is working correctly
https://github.com/spatie/crawler/blob/17beb464169487304007f6d856f6ef1e42800ad7/tests/CrawlerTest.php#L478

Could you submit a failing test for us to look at?

**Comment by flmommens** [comment]
```
<?php
require __DIR__ . '/vendor/autoload.php';
use Spatie\Crawler\Crawler;
use Spatie\Crawler\CrawlInternalUrls;
use Spatie\Crawler\CrawlObserver;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\UriInterface;

class IndexerCrawlObserver extends CrawlObserver
{
    protected $indexer;
    protected $indexName;
    
    public function crawled(UriInterface $url, ResponseInterface $response, ?UriInterface $foundOnUrl = null)
    {
        echo "Crawled $url\n";
    }

    public function crawlFailed(UriInterface $url, RequestException $e, ?UriInterface $foundOnUrl = null)
    {
        echo sprintf("Failed crawling %s %s\n", $url, Psr7\Message::toString($e->getResponse()));
    }
}

class SpatieCrawler
{
    protected $crawler;
    
    public function __construct(ContainerBagInterface $bag = null)
    {
        $this->crawler = Crawler::create()->acceptNofollowLinks()->setParseableMimeTypes(['text/html']);
    }

    public function setCrawlObserver(CrawlObserver $observer)
    {
        $this->crawler->setCrawlObserver($observer);
    }
    
    public function crawl($url)
    {
        $this->crawler->setCrawlProfile(new CrawlInternalUrls($url));
        $this->crawler->startCrawling($url);
    }
}

$crawler = new SpatieCrawler();
$crawler->setCrawlObserver(new IndexerCrawlObserver());
$crawler->crawl('https://marketmegood.com/blog/');
```
After a short while, the IndexerCrawlObserver::crawled method starts being called with images:

```
Crawled https://marketmegood.com/blog/wp-content/uploads/2019/07/market.jpg
Crawled https://marketmegood.com/blog/wp-content/uploads/2019/10/SaaS.png
Crawled https://marketmegood.com/blog/wp-content/uploads/2019/07/picureineineine.jpg
```

**Comment by jay4yam** [comment]
Hi 
I've got the same issue, I add setParseableMimeTypes(['text/html', 'text/plain']) method, but it crawl also image/jpeg

`CrawlStart::create([
            RequestOptions::ALLOW_REDIRECTS => true,
            'headers' => [
            'User-Agent' => 'mybot',
            'Accept' => 'text/html,application/xhtml+xml',
            'Accept-Encoding' => 'gzip, deflate, br',
            ],
            ])->setParseableMimeTypes(['text/html', 'text/plain'])
            ->setDelayBetweenRequests(100)
            ->doNotExecuteJavaScript()
            ->respectRobots()
            ->setCrawlProfile(new CrawlInternalUrls($site2crawl))
            ->setCrawlObserver(new Crawler($site2crawl))
            ->startCrawling($site2crawl->tld);`


I need to add a test in the crawled function into crawlObserver to avoid other mime/types.

thanks for your help.

**Comment by rayrutjes** [comment]
I'm currently playing with this great package.


I've got the following:
```
$crawler->setParseableMimeTypes(['text/html', 'text/plain']);
```

Yet the observer `crawled` is called even if the mime type isn't matched.

From what I gathered, [`CrawlRequestFulfilled::isMimetypeAllowedToParse`](https://github.com/spatie/crawler/blob/13b61b528e2915a7a077b35a4a29aa4e88950ab8/src/Handlers/CrawlRequestFulfilled.php#L133) is only called from [`CrawlRequestFulfilled::getBody()`](https://github.com/spatie/crawler/blob/main/src/Handlers/CrawlRequestFulfilled.php#L90), and it just sets the body to an empty string.
Then regardless of the check, it calls [`handleCrawled`](https://github.com/spatie/crawler/blob/13b61b528e2915a7a077b35a4a29aa4e88950ab8/src/Handlers/CrawlRequestFulfilled.php#L50).

So in the current state it seems logic that the observer gets to process all the URLs regardless of the mimeType.

I'm curious to know if that was the intention. Seems counterintuitive but I might miss something.


Then what really caught me off guard was [the trick here](https://github.com/spatie/crawler/blob/13b61b528e2915a7a077b35a4a29aa4e88950ab8/src/Handlers/CrawlRequestFulfilled.php#L46-L47). We create a response passing down the initial response but set a `cachedBody` field.

This means indeed that from the observer, you need to call `$response->getCachedBody()` and not `$response->getBody()->getContents()`. The later would result in reading all the data regardless of any crawler config.
Because of this behaviour, one can also think that the `maxResponseSize` configuration is not working. 

I'd be more than happy to contribute if I have some time, but I first wanted to make sure those 2 behaviours weren't intended.
